import { BotCommandBuilder } from "phasebot/builders"

export default new BotCommandBuilder()
  .setName("catfact")
  .setDescription("Gives you an interesting fact about cats.")
  .setExecute(async (interaction) => {
    const factIndex = Math.floor(Math.random() * facts.length)
    const fact = facts[factIndex]!
    return void interaction.reply(fact)
  })

const facts = [
  "Cats have been domesticated for over 9,000 years.",
  'A group of cats is called a "clowder."',
  "A cat's nose is as unique as a human fingerprint.",
  "Cats can make over 100 different sounds.",
  "Cats sleep for about 13 to 16 hours a day.",
  "They have a reflective layer behind their retinas called the tapetum lucidum, which helps them see in the dark.",
  "A cat’s purring can promote healing and reduce stress.",
  "Domestic cats can run up to 30 miles per hour.",
  "Cats have retractable claws to protect them while they hunt.",
  "A cat's whiskers are roughly the width of their body and help them gauge spaces.",
  "The largest breed of domesticated cat is the Maine Coon.",
  "Cats have five toes on their front paws but only four on their back paws.",
  "A cat's brain is 90% similar to a human’s.",
  "They have a Jacobson's organ, allowing them to taste scents.",
  "Cats can jump up to six times their body length in one leap.",
  "The world’s oldest known pet cat was found in a 9,500-year-old grave on Cyprus.",
  "The average cat’s heartbeat is between 140-220 beats per minute.",
  "Cats sweat through their paws.",
  "They can rotate their ears 180 degrees.",
  "The record for the longest cat ever is over 48 inches.",
  "A cat's purr vibrates at a frequency between 25 and 150 Hz, similar to the frequency used in vibrational therapies.",
  "Cats can’t taste sweetness.",
  "There are more than 500 million domestic cats in the world.",
  "Each cat's coat pattern is unique.",
  "Black cats are considered good luck in the UK and Japan.",
  "Cats can be right-pawed or left-pawed.",
  "Cats communicate using a combination of vocalizations, body language, and scent.",
  "The first cat show was held in 1871 in London.",
  "A cat’s grooming can help cool it down and regulate its body temperature.",
  "Cats have a third eyelid called a “haw.”",
  "A cat’s tail contains about 10% of its bones.",
  "The Egyptian Mau is the fastest domestic cat breed.",
  "Cats knead with their paws when they’re feeling relaxed or content.",
  "The average lifespan of an indoor cat is 12-15 years.",
  "In ancient Egypt, cats were revered and often mummified.",
  "Cats use their tails for balance.",
  "They can’t see directly under their noses.",
  "Cats’ tongues have tiny, hook-like structures called papillae that help them groom.",
  'A group of kittens is called a "kindle."',
  "Cats' eyes glow in the dark due to the tapetum lucidum.",
  "A domestic cat's sense of smell is about 14 times stronger than a human’s.",
  "Cats have an extra organ that allows them to taste smells, called the vomeronasal organ.",
  "Cats can dream during sleep.",
  "A cat's hearing is among the best in the animal kingdom, detecting frequencies up to 64 kHz.",
  "Most cats don’t like water because their fur doesn’t dry quickly.",
  "Cats can’t move their jaws sideways.",
  "The smallest wild cat species is the rusty-spotted cat from India and Sri Lanka.",
  "Cats are lactose intolerant.",
  "A cat’s collarbone is unattached to other bones, allowing it to squeeze through tight spaces.",
  "The world's richest cat, Blackie, inherited £7 million after its owner passed away.",
  "Cats are more sensitive to vibrations than humans, which helps them detect earthquakes.",
  "Calico cats are almost always female.",
  "Cats have 230 bones, while humans have 206.",
  "Cats don't have a sweet tooth due to a genetic defect.",
  "Some cats have thumbs—this condition is called polydactylism.",
  "Cats spend around a third of their waking hours grooming.",
  "The “slow blink” from a cat is a sign of trust and affection.",
  "Cats can make up to 10 different types of vocalizations to communicate with humans.",
  "They can get “zoomies” from pent-up energy.",
  "The world’s fattest cat weighed 46 pounds.",
  "Catnip affects about 50% of cats.",
  "A cat's back is extremely flexible due to its loosely fitting vertebrae.",
  "Cats use their whiskers to detect changes in their environment.",
  'A pregnant cat is called a "queen."',
  "Cats rarely meow at other cats; it's usually a behavior aimed at humans.",
  "The oldest recorded living cat was 38 years old.",
  "A domestic cat's hunting instinct is triggered by movement.",
  "Cats can drink seawater; their kidneys can filter out the salt.",
  "They have two sets of vocal cords, one for purring and one for other sounds.",
  "Some cats “chirp” or “chatter” when observing birds.",
  "They can survive falls from high places, a phenomenon called the “cat righting reflex.”",
  "Cats have been known to walk great distances to return to their homes.",
  "A cat's tail position and movement can signal its mood.",
  "Their primary sense is smell, followed by hearing and sight.",
  "The domestic cat shares about 95.6% of its DNA with tigers.",
  "Most cats can’t fully digest cow’s milk.",
  "Cats' pupils can dilate up to three times their normal size.",
  "A neutered cat generally lives longer than one that isn’t.",
  'They can "chirp" at birds and other small animals they see outside.',
  "Cats prefer to be in higher places to feel secure.",
  "Domestic cats retain many traits from their wild ancestors.",
  "Cats may purr when they are in pain as a self-soothing mechanism.",
  "The Scottish Fold breed has unique folded ears.",
  "Their fur can change color if exposed to the sun for prolonged periods.",
  "Cats are capable of producing more than 60 offspring in their lifetime.",
  "Cats' fur can thicken as winter approaches to protect against cold.",
  "They tend to favor one paw over the other, similar to human handedness.",
  "Cats are territorial and use scent glands on their face and paws to mark their space.",
  "A cat’s purring can lower stress and blood pressure for humans.",
  'They have "whisker fatigue" when their sensitive whiskers are overstimulated.',
  "The Sphynx breed is hairless and known for being affectionate.",
  "Cats are obligate carnivores, meaning they require meat in their diet.",
  "Cats' eyes take time to adjust to different lighting conditions.",
  "Tortoiseshell cats are almost always female due to genetics.",
  "Cats generally groom themselves after eating to hide their scent from predators.",
  "The Bombay cat was bred to resemble a panther.",
  "Cats have sharp night vision, needing only one-sixth of the light humans do to see clearly.",
  "Cats are crepuscular, meaning they are most active at dawn and dusk.",
  "The Turkish Van breed is known for its love of water.",
  "Cats don’t usually like change, preferring a consistent routine and environment.",
]
