name: "🐛 Bug report"
description: Report a bug you've encountered
labels: ["bug report"]
assignees: ""

body:
  - type: textarea
    id: bug_description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "Describe the bug here"
    validations:
      required: true

  - type: textarea
    id: expected_behaviour
    attributes:
      label: "Expected behaviour"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "Expected behaviour here"
    validations:
      required: true

  - type: textarea
    id: current_behaviour
    attributes:
      label: "Current behaviour"
      description: "A clear and concise description of what is currently happening."
      placeholder: "Current behaviour here"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps To reproduce"
      description: "Steps to reproduce the behaviour."
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."
      placeholder: "Add a link to screenshots or images here"

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
      placeholder: "Additional information"
