import * as Discord from 'discord.js'
import * as Utils from '#src/utils/index.js'
import * as Schemas from '@repo/utils/schemas'


export default Utils.clientSlashCommand({
  data: new Discord.SlashCommandBuilder()
    .setName('compliment')
    .setDescription('Generates a personal compliment for you!'),
  async execute(client, interaction) {

    const compliments = [
      "You have a great sense of humor.",
      "You're an inspiration to others.",
      "Your smile is beautiful.",
      "You're an excellent listener.",
      "Your positive attitude is contagious.",
      "You're intelligent and articulate.",
      "Your work ethic is strong.",
      "You're so talented at everything you do.",
      "You're a natural leader.",
      "Your fashion sense is great.",
      "You're kind and caring.",
      "Your soul is beautiful.",
      "Your perspective on things is unique.",
      "Your energy is infectious and brightens up a room.",
      "You're a great problem solver.",
      "Your heart is made of gold.",
      "You have a great memory for details.",
      "You're a great communicator.",
      "Your singing voice is beautiful.",
      "Your sense of style is great.",
      "You have a magnetic personality.",
      "You're a true team player.",
      "You're a great cook.",
      "Your sense of empathy is strong.",
      "You're a skilled athlete.",
      "Your sense of humor is contagious.",
      "You have a beautiful way with words.",
      "Your sense of adventure is great.",
      "Your mind is beautiful.",
      "You're a true inspiration to those around you.",
      "You're a true creative force.",
      "Your passion for life is infectious.",
      "You're an exceptional listener.",
      "Your heart is made of gold.",
      "You have an uncanny ability to make others feel comfortable.",
      "Your sense of style is wonderful.",
      "You're a natural leader.",
      "Your mind is beautiful.",
      "Your work ethic is great.",
      "Your positive attitude is contagious.",
      "You're an inspiring individual.",
      "You have a unique and special gift.",
      "Your mind is brilliant.",
      "Your personality is amazing.",
      "You have a wonderful way with words.",
      "Your heart is beautiful.",
      "You have a special talent that sets you apart.",
      "Your energy is infectious and people gravitate towards you.",
      "Your sense of adventure is great.",
      "You're a true optimist.",
      "You're a great motivator.",
      "You have an uncanny ability to make others laugh.",
      "Your natural charm draws people to you.",
      "Your eye for detail is great.",
      "Your sense of humor is wonderful and lifts people's spirits.",
      "Your grace and elegance is natural.",
      "You have a magnetic personality.",
      "Your heart is full of compassion.",
      "You have a captivating presence.",
      "Your creativity knows no bounds.",
      "Your voice is soothing and comforting.",
      "You always know how to make people feel welcome.",
      "You have a genuine and kind heart.",
      "Your energy is calming and peaceful.",
      "Your intelligence and insight is impressive.",
      "You have a natural talent for problem-solving.",
      "Your resilience and strength is admirable.",
      "You have a contagious zest for life.",
      "Your generosity and selflessness is inspiring.",
      "You radiate confidence and poise.",
      "Your determination and perseverance is remarkable.",
      "Your curiosity and thirst for knowledge is admirable.",
      "You have a wonderful sense of humor that brightens everyone's day.",
      "Your honesty and authenticity is refreshing.",
      "You have a natural talent for bringing people together.",
      "Your compassion and empathy is unmatched.",
      "You have a remarkable ability to inspire others.",
      "Your intuition and understanding is remarkable.",
      "You have an infectious laugh that makes everyone smile.",
      "Your positive attitude is a breath of fresh air.",
      "You have a genuine interest in other people and their stories.",
      "Your presence alone brings joy and positivity.",
      "You have a unique and creative perspective on the world.",
      "Your dedication and commitment to your passions is inspiring.",
      "You have a natural charisma that draws people towards you.",
      "Your open-mindedness and willingness to learn is admirable.",
      "You have an innate ability to make people feel valued and appreciated.",
      "Your generosity of spirit and kindness knows no bounds.",
      "You have a natural talent for connecting with people on a deep level.",
      "Your positivity is infectious and uplifting.",
      "You have a unique and beautiful perspective on life.",
      "Your determination and drive is inspiring.",
      "Your kindness and compassion is unmatched.",
      "You have a natural talent for bringing out the best in others.",
      "Your creativity and imagination is boundless.",
      "Your strength and resilience is admirable.",
      "You have a genuine and infectious passion for life.",
      "Your inner beauty shines through in everything you do.",
      "You have a wonderful sense of humor that always brings a smile to people's faces.",
      "Your empathy and understanding is truly remarkable.",
      "You have a natural talent for making people feel heard and understood.",
      "Your kindness and generosity knows no bounds.",
      "You have a contagious energy that inspires those around you.",
      "Your unwavering dedication to your goals and dreams is truly admirable.",
      "Your intelligence and wisdom is impressive.",
      "You have a natural ability to make people feel comfortable and at ease.",
      "Your optimism and positive outlook on life is infectious.",
      "You have a remarkable ability to connect with people on a deep level.",
      "Your authenticity and honesty is refreshing and rare.",
      "You have a unique and captivating presence that draws people towards you.",
      "Your thoughtfulness and consideration for others is truly special.",
      "Your creativity and innovation is truly impressive.",
      "You have a natural talent for seeing the beauty in everything and everyone.",
      "Your ability to inspire others to be their best selves is truly remarkable.",
      "Your courage and bravery is inspiring and admirable.",
      "Your open-mindedness and willingness to learn is truly admirable.",
      "You have a wonderful way with words that always leaves people feeling inspired.",
      "Your generosity of spirit and willingness to help others is truly selfless.",
      "You have a beautiful and infectious laugh that always brings joy to those around you.",
    ]

    interaction.reply(compliments[Math.floor(Math.random() * compliments.length)])

  }
})